# CI pipeline configuration
# https://aka.ms/yaml

trigger:
  - main

variables:
  TEST_OUTPUT_DIRECTORY: $(Build.Repository.LocalPath)/ChatGPS/testresults
  BuildConfiguration: Release

jobs:
- job: BuildWithTests
  displayName: 'Build and test ChatGPS PowerShell module'
  strategy:
    matrix:
      PowerShellCoreWindows:
        VM_IMAGE: 'windows-latest'
        OS_PLATFORM: 'windows'
        USE_POWERSHELL_CORE: true
      PowerShellCoreUbuntu:
        VM_IMAGE: 'ubuntu-latest'
        OS_PLATFORM: 'ubuntu'
        USE_POWERSHELL_CORE: true
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - checkout: self

  - task: powershell@2
    displayName: 'Show current PowerShell version information'
    inputs:
      targetType: inline
      script: 'echo $PSVersionTable'
      pwsh: $(USE_POWERSHELL_CORE)

  - task: UseDotNet@2
    displayName: 'Install and configure build tools'
    inputs:
      version: 8.x
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: 'Build module package'
    inputs:
      command: build
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      custom: msbuild
      arguments: './ChatGPS/ChatGPS.csproj --target:UnitTestPowerShellModule -p:Configuration=$(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish module for local testing'
    inputs:
      command: build
      arguments: './ChatGPS/ChatGPS.csproj --target:PublishModule --configuration $(BuildConfiguration)'

  - task: PublishTestResults@2
    inputs:
      searchFolder: $(TEST_OUTPUT_DIRECTORY)
      testResultsFormat: NUnit
      testResultsFiles: '*.xml'
      failTaskOnFailedTests: true
